"""
Database models for Kitchen Smart Inventory application.

This module defines all SQLModel classes that represent database tables.
SQLModel combines SQLAlchemy (for database operations) with
Pydantic (for data validation).

Models:
- Location: Physical locations in the kitchen (e.g., Fridge, Pantry)
- Store: Shops where products can be purchased (e.g., Lidl, Mercadona)
- Product: Catalog definition of items (e.g., "Milk 3.2%", "Eggs M 10-pack")
- InventoryItem: Physical instances of products in specific locations

All models include automatic `created_at` and `updated_at` timestamps via
the `TimestampMixin` (database-level defaults and on-update behavior).
"""

from datetime import date, datetime
from typing import Optional
from sqlmodel import Field, SQLModel
from sqlalchemy import Column, DateTime, func
from sqlalchemy.ext.declarative import declared_attr


class TimestampMixin:
    @declared_attr
    def created_at(cls):
        return Column(DateTime(timezone=True), server_default=func.now())

    @declared_attr
    def updated_at(cls):
        return Column(
            DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
        )


class Location(SQLModel, TimestampMixin, table=True):
    """
    Represents a physical location in the kitchen where items are stored.

    Examples: "Fridge", "Freezer", "Pantry", "Upper Cabinet"

    Includes automatic created_at / updated_at timestamps.
    """

    # Primary key - automatically generated by database
    id: Optional[int] = Field(default=None, primary_key=True)

    # Location name - indexed for fast searches
    name: str = Field(index=True)


class Store(SQLModel, TimestampMixin, table=True):
    """
    Represents a store where products can be purchased.

    Examples: "Lidl", "Mercadona", "Dia", "Local Market"

    Includes automatic created_at / updated_at timestamps.
    """

    # Primary key - automatically generated by database
    id: Optional[int] = Field(default=None, primary_key=True)

    # Store name - indexed for fast searches
    name: str = Field(index=True)


class Product(SQLModel, TimestampMixin, table=True):
    """
    Represents a product catalog definition (not a physical item).

    This is the "template" for items - it defines what the product IS,
    not where it is or how many we have.

    Examples:
    - name="Milk", brand="Łaciate"
    - name="Eggs M 10-pack", brand="None"

    Includes automatic created_at / updated_at timestamps.
    """

    # Primary key - automatically generated by database
    id: Optional[int] = Field(default=None, primary_key=True)

    # Product name - indexed for fast searches (e.g., searching for "milk")
    name: str = Field(index=True)

    # Brand name - optional and indexed (e.g., filter by brand "Łaciate")
    brand: Optional[str] = Field(default=None, index=True)


class InventoryItem(SQLModel, TimestampMixin, table=True):
    """
    Represents a physical instance of a product in inventory.

    This is the CORE model - it connects everything together:
    - WHAT: Links to a Product (what item is this?)
    - WHERE: Links to a Location (where is it stored?)
    - FROM WHERE: Links to a Store (where was it bought? - optional)
    - HOW MUCH: quantity, price, dates

    Example:
    - Product: "Milk 3.2%"
    - Location: "Fridge"
    - Store: "Mercadona"
    - Quantity: 1.0
    - Expiration: 2025-11-15

    Includes automatic created_at / updated_at timestamps.
    """

    # Primary key - automatically generated by database
    id: Optional[int] = Field(default=None, primary_key=True)

    # Item properties
    quantity: float = Field(
        default=1.0
    )  # Allows partial items like 0.5 kg or 2.5 liters
    purchase_date: Optional[date] = Field(default=None)  # When was it bought?
    expiration_date: Optional[date] = Field(default=None)  # When does it expire?
    price: Optional[float] = Field(default=None)  # How much did it cost?

    # Foreign keys - relationships to other tables
    # These create the relational database structure

    product_id: int = Field(
        foreign_key="product.id"
    )  # REQUIRED: Every item must be a product - links to Product.id

    location_id: int = Field(
        foreign_key="location.id"
    )  # REQUIRED: Every item must be somewhere - links to Location.id

    store_id: Optional[int] = Field(
        default=None, foreign_key="store.id"
    )  # OPTIONAL: We might not know where it was bought - links to Store.id


# ============================================================================
# Response Schemas (to include timestamps in API responses)
# ============================================================================


class LocationRead(SQLModel):
    id: int
    name: str
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class StoreRead(SQLModel):
    id: int
    name: str
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
